#!/usr/bin/env python3
from __future__ import annotations

import argparse
import signal
import subprocess
import sys
import tempfile
import time
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND_DIR = REPO_ROOT / "apps" / "backend"
MINIAPP_DIR = REPO_ROOT / "apps" / "miniapp"
ROOT_ENV_PATH = REPO_ROOT / ".env"
BACKEND_DEV_VARS_PATH = BACKEND_DIR / ".dev.vars"
MINIAPP_DEV_VARS_PATH = MINIAPP_DIR / ".dev.vars"
MINIAPP_ENV_LOCAL_PATH = MINIAPP_DIR / ".env.local"
BACKEND_WORKER_NAME = "kassir-backend"
MINIAPP_PROJECT_NAME = "kassir-miniapp"

BACKEND_SECRET_KEYS = [
    "BOT_TOKEN",
    "SUPABASE_URL",
    "SUPABASE_ANON_KEY",
    "SUPABASE_SERVICE_ROLE_KEY",
    "OPENAI_API_KEY",
    "CRON_SECRET",
    "LOG_CHANNEL_ID",
]

BACKEND_OPTIONAL_KEYS = [
    "SUPABASE_KEY",
    "ADMIN_IDS",
    "OWNER_ID",
    "BOT_USERNAME",
    "WEBAPP_URL",
    "TELEGRAM_LOGGING_ENABLED",
    "LOG_LEVEL",
    "LOCAL_LOG_LEVEL",
]

DEFAULT_MINIAPP_BACKEND_ORIGIN = "http://127.0.0.1:8787"


def parse_env_file(path: Path) -> dict[str, str]:
    data: dict[str, str] = {}
    if not path.exists():
        return data

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if value[:1] == value[-1:] and value[:1] in {"'", '"'}:
            value = value[1:-1]
        data[key] = value
    return data


def quote_env_value(value: str) -> str:
    escaped = (
        str(value)
        .replace("\\", "\\\\")
        .replace("\n", "\\n")
        .replace('"', '\\"')
    )
    return f'"{escaped}"'


def write_env_file(path: Path, values: dict[str, str], title: str) -> None:
    lines = [f"# {title}"]
    for key in sorted(values):
        lines.append(f"{key}={quote_env_value(values[key])}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_backend_secret_payload(values: dict[str, str]) -> str:
    lines = ["# Generated secret payload for wrangler secret bulk"]
    for key in BACKEND_SECRET_KEYS:
        value = values.get(key, "").strip()
        if value:
            lines.append(f"{key}={quote_env_value(value)}")
    return "\n".join(lines) + "\n"


def ensure_split_env_files() -> tuple[dict[str, str], dict[str, str]]:
    root_env = parse_env_file(ROOT_ENV_PATH)
    if not root_env:
        raise SystemExit(
            f"Root env topilmadi yoki bo'sh: {ROOT_ENV_PATH}"
        )

    service_role = (
        root_env.get("SUPABASE_SERVICE_ROLE_KEY")
        or root_env.get("SUPABASE_KEY")
        or ""
    ).strip()

    backend_env: dict[str, str] = {}
    for key in BACKEND_SECRET_KEYS:
        if key == "SUPABASE_SERVICE_ROLE_KEY":
            if service_role:
                backend_env[key] = service_role
            continue
        value = root_env.get(key, "").strip()
        if value:
            backend_env[key] = value

    if service_role:
        backend_env["SUPABASE_KEY"] = service_role

    for key in BACKEND_OPTIONAL_KEYS:
        value = root_env.get(key, "").strip()
        if value:
            backend_env[key] = value

    backend_env.setdefault("TELEGRAM_LOGGING_ENABLED", "true")
    backend_env.setdefault("LOG_LEVEL", "INFO")
    backend_env.setdefault("LOCAL_LOG_LEVEL", "ERROR")

    backend_origin = root_env.get("BACKEND_ORIGIN", "").strip() or DEFAULT_MINIAPP_BACKEND_ORIGIN

    miniapp_dev_vars = {
        "PUBLIC_API_BASE_URL": backend_origin,
    }
    miniapp_env_local = {
        "KASSA_BACKEND_ORIGIN": backend_origin,
    }

    write_env_file(
        BACKEND_DEV_VARS_PATH,
        backend_env,
        "Generated by scripts/kassir_cloudflare.py for Cloudflare Worker local dev",
    )
    write_env_file(
        MINIAPP_DEV_VARS_PATH,
        miniapp_dev_vars,
        "Generated by scripts/kassir_cloudflare.py for Cloudflare Pages fallback proxy",
    )
    write_env_file(
        MINIAPP_ENV_LOCAL_PATH,
        miniapp_env_local,
        "Generated by scripts/kassir_cloudflare.py for Vite proxy",
    )
    return backend_env, root_env


def run_command(command: list[str], cwd: Path | None = None) -> None:
    subprocess.run(command, cwd=cwd or REPO_ROOT, check=True)


def run_split_env(_args: argparse.Namespace) -> int:
    ensure_split_env_files()
    print(f"Wrote {BACKEND_DEV_VARS_PATH}")
    print(f"Wrote {MINIAPP_DEV_VARS_PATH}")
    print(f"Wrote {MINIAPP_ENV_LOCAL_PATH}")
    return 0


def run_dev(_args: argparse.Namespace) -> int:
    ensure_split_env_files()
    processes = [
        subprocess.Popen(
            [
                "npx",
                "wrangler",
                "dev",
                "--config",
                str(BACKEND_DIR / "wrangler.jsonc"),
                "--local",
            ],
            cwd=REPO_ROOT,
        ),
        subprocess.Popen(
            [
                "npx",
                "vite",
                "--config",
                str(MINIAPP_DIR / "vite.config.mjs"),
            ],
            cwd=REPO_ROOT,
        ),
    ]

    def stop_all(*_signal_args) -> None:
        for process in processes:
            if process.poll() is None:
                process.terminate()

    signal.signal(signal.SIGINT, stop_all)
    signal.signal(signal.SIGTERM, stop_all)

    exit_codes: list[int | None] = [None for _ in processes]
    try:
        while True:
            exit_codes = [process.poll() for process in processes]
            if any(code is not None for code in exit_codes):
                break
            time.sleep(0.25)
    finally:
        stop_all()
        for process in processes:
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()

    normalized_exit_codes = [code for code in exit_codes if code is not None]
    return max(normalized_exit_codes or [0])


def run_build(_args: argparse.Namespace) -> int:
    ensure_split_env_files()
    run_command(["npm", "run", "build:miniapp"])
    return 0


def run_deploy_backend(args: argparse.Namespace) -> int:
    backend_env, _root_env = ensure_split_env_files()
    if not args.skip_secret_sync:
        with tempfile.NamedTemporaryFile("w", encoding="utf-8", suffix=".env", delete=False) as temp_file:
            temp_file.write(build_backend_secret_payload(backend_env))
            temp_file_path = Path(temp_file.name)
        try:
            run_command(
                [
                    "npx",
                    "wrangler",
                    "secret",
                    "bulk",
                    str(temp_file_path),
                    "--config",
                    str(BACKEND_DIR / "wrangler.jsonc"),
                ]
            )
        finally:
            temp_file_path.unlink(missing_ok=True)
    run_command(
        [
            "npx",
            "wrangler",
            "deploy",
            "--config",
            str(BACKEND_DIR / "wrangler.jsonc"),
            "--name",
            BACKEND_WORKER_NAME,
        ]
    )
    return 0


def run_deploy_miniapp(_args: argparse.Namespace) -> int:
    ensure_split_env_files()
    run_command(["npm", "run", "build:miniapp"])
    run_command(
        [
            "npx",
            "wrangler",
            "pages",
            "deploy",
            "dist",
            "--project-name",
            MINIAPP_PROJECT_NAME,
            "--branch",
            "main",
            "--commit-dirty=true",
            "--cwd",
            str(MINIAPP_DIR),
        ]
    )
    return 0


def run_deploy(args: argparse.Namespace) -> int:
    run_deploy_backend(args)
    run_deploy_miniapp(args)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Kassir Cloudflare backend + mini app orchestration helper",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    split_env = subparsers.add_parser("split-env", help="Root .env dan app env fayllarini yaratish")
    split_env.set_defaults(func=run_split_env)

    dev = subparsers.add_parser("dev", help="Backend Worker va mini app dev serverlarini birga ishga tushirish")
    dev.set_defaults(func=run_dev)

    build = subparsers.add_parser("build", help="Mini app build")
    build.set_defaults(func=run_build)

    deploy_backend = subparsers.add_parser("deploy-backend", help="Backend Worker secret sync va deploy")
    deploy_backend.add_argument(
        "--skip-secret-sync",
        action="store_true",
        help="Cloudflare'ga secret bulk yuborishni o'tkazib yuborish",
    )
    deploy_backend.set_defaults(func=run_deploy_backend)

    deploy_miniapp = subparsers.add_parser("deploy-miniapp", help="Mini app Pages build va deploy")
    deploy_miniapp.set_defaults(func=run_deploy_miniapp)

    deploy = subparsers.add_parser("deploy", help="Backend va mini app'ni ketma-ket deploy qilish")
    deploy.add_argument(
        "--skip-secret-sync",
        action="store_true",
        help="Cloudflare'ga secret bulk yuborishni o'tkazib yuborish",
    )
    deploy.set_defaults(func=run_deploy)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    sys.exit(main())
